site_name: Tedeapolis wet en regelgeving
site_description: 'wet en regelgeving van tedeapolis roleplay'
site_author: 'Tedeapolis'
site_url: https://wetboek.tedeapolis.nl/
repo_url: https://github.com/Tedeapolis/wet-en-regelgeving/
repo_name: Tedeapolis/wet-en-regelgeving
google_analytics: ['UA-167800475-2', 'wetboek.tedeapolis.nl']
theme:
  name: material
  palette:
    scheme: preference
  favicon: img/logoTedeapolis.png
  logo: img/logoTedeapolis.png
  custom_dir: docs/overrides
plugins:
  - git-revision-date-localized:
      type: timeago
      time_zone: Europe/Amsterdam
      locale: en
      fallback_to_build_date: false
  # - git-authors